config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  get 'signup', to: 'users#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true, length: { minimum: 1 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { minimum: 3, maximum: 20 }, uniqueness: { case_sensitive: false }
  has_many :messages
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    #use memoization to speed up this method
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in first"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", mod_message: message_render(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to root_path
    else
      flash.now[:error] = "Either username or password is invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

  private
  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<!-- Header -->
<h2 class="ui center aligned icon header">
  <i class="circular orange users icon"></i>
  Start chatting with your friends!
</h2>

<div class="ui two column grid">

  <!-- Chat Room -->
  <div class="twelve wide column">
    <div class="ui card fluid raised chatBox">
      <div class="content" id="content-container">
        <div class="ui small feed" id="message-container">
          <h4 class="ui header">Chat Room</h4>
          <%= render @messages%>
        </div>
      </div>

      <div class="extra content">
        <%= form_for(@message, html: {class:"ui reply form", role: "form", remote: true}, url: message_path) do |f| %>
          <div class="ui action input fluid">
            <%= f.text_field :body, placeholder: "Enter your message here"%>
            <%= f.button 'Send', class: "ui button orange"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Vertical Menu -->
  <div class="four wide column chatBox">
    <div class="ui card fluid raised">
      <div class="content">
        <div class="ui vertical menu inverted fluid">
          <a class="active item">
            Account
          </a>
          <a class="item">
            Settings
          </a>
          <div class="ui dropdown item">
            <i class="dropdown icon"></i>
            Display Options
            <div class="menu">
              <div class="header">Text Size</div>
              <a class="item">Small</a>
              <a class="item">Medium</a>
              <a class="item">Large</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
  <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui large menu inverted">
  <div class="ui container">
    <a class="item">
      Home
    </a>
    <%= link_to 'Chat Room', root_path, class:'item' %>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to 'Log out', logout_path, method: :delete, class:'item' %>
          <% else %>
            <%= link_to 'Log in', login_path, class:'item' %>
          <% end %>
        </div>
      </div>
      <% if !logged_in? %>
        <div class="item">
            <div class="ui primary button">Sign Up</div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= action_cable_meta_tag %>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
       <a><%= message.user.username%></a>: <%= message.body%>
    </div>
  </div>
</div>